package forum::Model::Forum;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
use utf8;

__PACKAGE__->config(
    schema_class => 'Forum::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:forum',
        user => 'root',
        password => '',
	{
            AutoCommit        => 1,
            RaiseError        => 1,
            mysql_enable_utf8 => 1,                                   
        },
    }
);

=head1 NAME

forum::Model::Forum - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<forum>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Forum::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

minhbkpro

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
